# 临时邮箱服务配置
server:
  host: "0.0.0.0"
  port: 8000  # WebSocket API端口
  reload: false  # 生产环境设为false

# SMTP服务器配置
smtp:
  host: "0.0.0.0"  # SMTP监听地址
  port: 8025  # SMTP端口(建议使用非特权端口,生产环境用iptables转发25->8025)
  
  # 邮箱域名(只接收这个域名的邮件)
  allowed_domain: "example.com"  # 改成你的域名,如 your-domain.com
  
  # 注意: 生产环境需要配置DNS MX记录指向这台服务器

# 监控配置
monitor:
  max_connections: 10  # 最大同时监控连接数
  timeout: 300  # WebSocket超时时间(秒),超时后自动断开连接

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/rubbish_mail.log"

