version: '3.8'

services:
  rubbish-mail:
    build: .
    image: rubbish-mail:latest
    container_name: rubbish-mail
    
    # 端口映射
    ports:
      - "8000:8000"   # WebSocket API
      - "25:8025"     # SMTP服务器(主机25 -> 容器8025)
    
    # 环境变量
    environment:
      - API_KEY=${API_KEY:-your-api-key-here}
      - TZ=Asia/Shanghai
    
    # 卷挂载
    volumes:
      # 配置文件
      - ./config.yml:/app/config.yml:ro
      # 日志持久化
      - ./logs:/app/logs
      # 可选: 挂载自定义.env
      # - ./.env:/app/.env:ro
    
    # 重启策略
    restart: unless-stopped
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

